source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target "AdidasEvents" do
  pod 'Alamofire', '~> 4.0.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.0'
  pod 'SDWebImage', '~>3.7'
  pod 'SVProgressHUD'
  pod 'JSQMessagesViewController'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
